// Copyright 2023 PythonDeployer (@PythonDeployer) & ephb
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define WEAR_LEVELING_SN32_EMULATION_PAGE_COUNT 35
#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#define ITON_BT_ENABLE_ACK

#define AUTO_SHIFT_REPEAT
#define AUTO_SHIFT_NO_AUTO_REPEAT
#define AUTO_SHIFT_TIMEOUT_PER_KEY

#define LSPO_KEYS KC_LSFT, KC_LSFT, KC_8
#define RSPC_KEYS KC_RSFT, KC_RSFT, KC_9
#define LCPO_KEYS KC_LCTL, KC_ALGR, KC_8
#define RCPC_KEYS KC_RCTL, KC_ALGR, KC_9
#define LAPO_KEYS KC_LALT, KC_ALGR, KC_7
#define RAPC_KEYS KC_RALT, KC_ALGR, KC_0

#define CLSPO_KEYS KC_LSFT, KC_TRANSPARENT, KC_LSFT, KC_8
#define CRSPC_KEYS KC_RSFT, KC_TRANSPARENT, KC_RSFT, KC_9
#define CLCPO_KEYS KC_LCTL, KC_TRANSPARENT, KC_ALGR, KC_8
#define CRCPC_KEYS KC_RCTL, KC_TRANSPARENT, KC_ALGR, KC_9
#define CLAPO_KEYS KC_LALT, KC_TRANSPARENT, KC_ALGR, KC_7
#define CRAPC_KEYS KC_RALT, KC_TRANSPARENT, KC_ALGR, KC_0


#define CLSPOEN_KEYS KC_LSFT, KC_TRANSPARENT, KC_LSFT, KC_9
#define CRSPCEN_KEYS KC_RSFT, KC_TRANSPARENT, KC_RSFT, KC_0
#define CLCPOEN_KEYS KC_LCTL, KC_TRANSPARENT, KC_TRANSPARENT, KC_LBRC
#define CRCPCEN_KEYS KC_RCTL, KC_TRANSPARENT, KC_TRANSPARENT, KC_RBRC
#define CLAPOEN_KEYS KC_LALT, KC_TRANSPARENT, KC_LSFT, KC_LBRC
#define CRAPCEN_KEYS KC_RALT, KC_TRANSPARENT, KC_RSFT, KC_RBRC
